### ISSUE TITLE
Add support for invisible reCAPTCHA

### ISSUE THREAD

**Issue by elmanvebs** [aerni/statamic-livewire-forms#11]
Hi,

Invisible captcha support anytime soon?

Thanks.

**Comment by aerni** [comment]
I currently have no plans to add this. But it sounds like a good feature request.

**Comment by aerni** [comment]
I took a closer look at this feature and couldn't find a good way to implement it. Closing this issue for now. I've got the idea saved in my backlog and might revisit it in the future.
