### ISSUE TITLE
Google Recaptcha not showing

### ISSUE THREAD

**Issue by samdgea** [aerni/statamic-livewire-forms#12]
Hi, 
I'm using recaptcha and i have set the `CAPTCHA_KEY` and `CAPTCHA_SECRET` to my `.env` file but still the captcha is not showing.

![Google reCaptcha not showing](https://cdn.abdilah.id/uploads/Screenshot-2021-09-08-231544.jpg)

after i see on DevTools / Inspect element it show that Invalid site Key.

![Details on DevTools](https://cdn.abdilah.id/uploads/Screenshot-2021-09-08-231708.jpg)

I've been double check that my CAPTCHA_KEY and CAPTCHA_SECRET was correct.

Nice plugin btw

**Comment by aerni** [comment]
Hi! I can't reproduce your issue. It's working for me. What version are you on? Did you try on a fresh install of the addon? There were some major breaking changes. If you published the views, you have to manually update them.

**Comment by samdgea** [comment]
Hi thanks for the reply, and sorry for late response.

I'm running on Statamic 3.2.4 Pro
And using Statamic Livewire Form 2.0.0
and yes, i try fresh install of the addon but still no luck

**Comment by aerni** [comment]
I just tried on a fresh install and can't reproduce this issue. It might be that your view and config was cached before you added the keys to your `.env`. Try to run `php artisan optimize:clear` and try again.

**Comment by samdgea** [comment]
Ok i try run `php artisan optimize:clear` but still not showing, but when using DevTools / Inspect Element there's no error says Error Invalid site key.

![Google reCaptcha still not showing](https://cdn.abdilah.id/uploads/Screenshot+2021-09-15+142249.jpg)

**Comment by aerni** [comment]
Sorry, I have no idea why this is not working for you. But I don't think this is an issue with this addon. The view and reCAPTCHA JavaScript seem to load correctly. There must be something else going on with your particular setup. You can always publish the views with `php please vendor:publish --tag=livewire-forms-views` and change the captcha view.
