### ISSUE TITLE
Required validation not applying to Select fields

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#13]
I have enabled the 'Required' toggle in the validation tab of a Select field but the form submits when leaving this field blank.

Seems like a bug? Thanks!

**Comment by aerni** [comment]
I can't reproduce this. It works fine for me. Please create a repo that reproduces this issue. Thanks.

**Comment by stuartcusackie** [comment]
Sorry, my bad. I had a value entered for my default option. Thanks for checking.
