### ISSUE TITLE
Use a single livewire component for all forms

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#2]
First of all - Fantastic package! It has saved me a tonne of work. I will be buying a licence later.

I'm just wondering about a small admin problem. I wanted to give some of my Statamic users the ability to create forms and add them to entries themselves - without my help, but I don't know if that's possible. I think I will have to run `php please make:livewire-form` for this.

So I am wondering, do we we really need a separate livewire component for each form? Or is there a way to automatically assign a default form component that all forms fall back to? For me, the contents of each form component will be exactly the same:

```
<form wire:submit.prevent="submit" class="w-full max-w-2xl">
    <div class="grid grid-cols-1 gap-8 md:grid-cols-12">
        @include('livewire-forms::fields')
        @include('livewire-forms::fields.submit')
        @include('livewire-forms::fields.honeypot')
        @include('livewire-forms::errors')
        @include('livewire-forms::success')
    </div>
</form>
```

No big deal anyway. Thanks for the great work, and for Swup Livewire also!

**Comment by aerni** [comment]
You can also dynamically render a form that was selected via Statamic's form fieldtype like this:

```html
<!-- Antlers -->
{{ livewire:form :form="field:handle" }}

<!-- Blade -->
<livewire:form :form="field:handle">
```

But that only solves part of your problem. Right now, the addon will look for a view named after the form's handle. Meaning you will have to create a new view for every Statamic form. This is intentional, as every form is unique and usually also needs a unique markup.

Do your Statamic forms all share the same markup? If this is a valid use case, I could easily add an option that allows setting a view on the component.

**Comment by stuartcusackie** [comment]
Yes, I think all of the forms will be indentical, only the fields will differ.

I use this line in a dynamic button component (which allows the user to choose a form):
<livewire:form :form="$form['handle']">

The $form could have been created through statamic control panel, and the user wouldn't have access 
to `php please make:livewire-form`

So yes, I think if I could set the view to use the same template each time then that would work. I just need to bypass the `php please` step.

I hope that all makes sense! Again, no big deal. My users probably won't be using this functionality for a long time.

**Comment by aerni** [comment]
I will add this functionality with the next release.

**Comment by aerni** [comment]
I just added this functionality in [release v1.1.0](https://github.com/aerni/statamic-livewire-forms/releases/tag/v1.1.0).

**Comment by stuartcusackie** [comment]
Thanks! Will check it out over the next day or two.
