### ISSUE TITLE
Line breaks missing in email template

### ISSUE THREAD

**Issue by MrMooky** [aerni/statamic-livewire-forms#38]
Not sure if this is a "bug" in the add-on itself, but when sending a multi-line message, there are no breaks in the email.

```
This is a test message

Here is a new line
```

will look like this in the email:

```
This is a test message Here is a new line
```

**Comment by aerni** [comment]
What kind of message is this? Where, how, and when does it appear?

**Comment by MrMooky** [comment]
> What kind of message is this?

The message within the email inbox. So when I have a textarea in the form and add text with line breaks, as mentioned in my initial post, this textarea content is not outputted correctly when viewing it in the inbox.

Again, I'm not sure if this is add-on related.

**Comment by MrMooky** [comment]
That fixed it, thanks. :)
