### ISSUE TITLE
Improve the error messages for fields without labels

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#4]
I have a newsletter form with a single field for the email address. I don't use a label for this field, just a placeholder. 

The error message looks like this:

![image](https://user-images.githubusercontent.com/20210934/126809081-a1bc8d07-6fe7-4b78-b9f0-b3dccddf0c1e.png)

![image](https://user-images.githubusercontent.com/20210934/126809180-119645c6-6f00-4b9a-9655-4d4d230a0fc4.png)

Can this fall back to the fieldname instead (without 'data.')?

Thanks!

**Comment by aerni** [comment]
The `display` property of a field is required for this addon to work.

I just released `v1.2.0-beta.3` that allows you to add `show_label: false` to your field to hide the label. That should achieve what you want.

**Comment by stuartcusackie** [comment]
Ah I see. This solution works fine. Thanks!
