### ISSUE TITLE
Use commands to create antlers files

### ISSUE THREAD

**Issue by j-jalving** [aerni/statamic-livewire-forms#40]
Is it possible to create Antlers files instead of Blade? All my views (including my Livewire components) are Antlers files, so it would be nice if my Livewire Form components are also Antlers files.

**Comment by aerni** [comment]
I initially supported Antlers. But soon dropped in it in favor of Blade. There are many features that wouldn't be possible with Antlers or that would be a major headache. That's why I stopped supporting it.
