### ISSUE TITLE
File uploads get lost after submit

### ISSUE THREAD

**Issue by j-jalving** [aerni/statamic-livewire-forms#47]
This week I got a message from my client that file uploads seemed to be broken on their form (it worked before). I tried debugging the issue, and it seems that file gets uploaded properly (I can see it I'n my assets). But then the field values gets cleared; it isn't attached to the e-email and the form submission in the CP doesn't show it either. 

When logging the field in the `submittedForm` hook, it shows the field has a value (field type `Livewire\TemporaryUploadedFile`). But when doing the same in the e-mail template, the value is empty (field type `Statamic\Fields\Value`).

I see there was an issue (#14) before, that was fixed last year. Could be that this bug has regressed with one of the latest Statamic updates?

**Comment by aerni** [comment]
I just tested this with the latest Statamic version. Everything works as expected on my end. What version of Statamic and Livewire Forms are you using? Can you reproduce the issue on a fresh installation?

**Comment by j-jalving** [comment]
I could not reproduce the issue on a fresh installation, apparently the issue was caused by another Statamic addon that clear the attachments. Pushed a fix to their repo.
