### ISSUE TITLE
Undocumented step required when using livewire:scriptConfig tag

### ISSUE THREAD

**Issue by godismyjudge95** [aerni/statamic-livewire-forms#52]
Found out the hard way that if you need to compile the Livewire assets separately (ie. to add an Alpine plugin) there is one additional step required.

I had assumed that by using the `{{ livewire:scriptConfig }}` tag the livewire forms script would be included.  However that appears to only set up some preliminary config variables.

I was able to get the forms working again by adding the following to by `site.js`:
```js
import { Livewire, Alpine } from "../../vendor/livewire/livewire/dist/livewire.esm";
import "../../vendor/aerni/livewire-forms/resources/dist/js/livewire-forms";

window.Alpine = Alpine;
Livewire.start();
```

**Comment by aerni** [comment]
Thanks for taking the time to figure this out. I just merged your PR.
