### ISSUE TITLE
Error when form contains a hidden field

### ISSUE THREAD

**Issue by j-jalving** [aerni/statamic-livewire-forms#54]
I'm in the process of updating to Statamic 5 / Livewire Forms 9, but I'm running into an error:

```
Call to a member function resetErrorBag() on null
```

This error occurs when a form contains a Hidden field or a Text field with the Input Type set as 'hidden', and can be easily replicated in a fresh install.

**Comment by aerni** [comment]
Thanks for raising this issue. I will release a fix shortly.
