### ISSUE TITLE
UndefinedContainerException when using multiple containers

### ISSUE THREAD

**Issue by j-jalving** [aerni/statamic-livewire-forms#56]
When using an Asset field in a project with multiple local containers configured, after submitting the error `UndefinedContainerException: An asset container has not been configured` is thrown. This happens even though the `container` option has been set.

Statamic seems to be unable to retrieve the field options inside Statamic's `AssetsUploader` class. In projects with only one container, the error does not occur because it will automatically pick that container without looking at the field options.

**Comment by aerni** [comment]
Thanks! Just released a fix.
