### ISSUE TITLE
Select field throws an error( Cannot access offset of type array on array )

### ISSUE THREAD

**Issue by Vuorenheimo** [aerni/statamic-livewire-forms#67]
Hello!

While using this extension, I noticed that when adding select field to form blueprint, I get mentioned error while rendering form in view.

## Steps to Reproduce
1. Create new form.
2. Add new blueprint.
3. Add select field to blueprint.
4. Add form to view, with `{{ livewire:form handle="{ form_name }" }}`
5. Error visible in rendering.

## Possible Solution
I think error is caused in [WithOptions trait](https://github.com/aerni/statamic-livewire-forms/blob/246a8f54b691662dea827c6074ec112e6e62e54e/src/Fields/Properties/WithOptions.php#L20) where mapWithKeys callback returns an associative array and array of options is passed as key to array.

## Context (Environment)
Happens on fresh install of Laravel 11.
```
"php": "^8.3",
"aerni/livewire-forms": "^9.3",
"laravel/framework": "^11.9",
"statamic/cms": "^5.22"
```

Anyway, thank you for this extension. Livewire for the win!

**Comment by niemenmaa** [comment]
This happens to me also (running Laravel 10, statamic 5, newest version of this package). 

Fixed by changing the line to

```
return collect($options)
            ->mapWithKeys(fn ($value) => [$value['key'] => __($value['value']  ?? $value['key']) ])
            ->toArray();
```

**Comment by aerni** [comment]
Looks like this bug was introduced with https://github.com/statamic/cms/pull/10336 in Statamic v5.21.0. I'll release a fix shortly.
