### ISSUE TITLE
Latest version of Statamic causes error

### ISSUE THREAD

**Issue by edalzell** [aerni/statamic-livewire-forms#70]
When I upgraded to Statamic v5.29 I got this:
<img width="1369" alt="image" src="https://github.com/user-attachments/assets/a8a2eaa4-43f6-44ce-bb96-eb656c65e9bc">

I suspect it has something to do with all the new auto-loading in 5.29:  https://github.com/statamic/cms/issues/10882

**Comment by duncanmcclean** [comment]
statamic/cms#10886 should fix this.

**Comment by aerni** [comment]
Thanks @duncanmcclean!
