### ISSUE TITLE
Support conditional logic

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#8]
Just out of curiousity, are you planning to handle conditional showing of fields based on Statamic field settings?

I don't need it but just wanted to let my client know if they can use conditional logic.

**Comment by aerni** [comment]
There are no plans right now. But this sounds like a cool enhancement for the future. I might tackle it at some point if there is more demand for it.

**Comment by aerni** [comment]
I just added this functionality on the main branch and will soon release it with a bunch of other improvements.

**Comment by stuartcusackie** [comment]
awesome. I'll check it out someday.
