### ISSUE TITLE
Question: Is there a solution to the csrf problem when using static caching?

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#9]
Just wondering, do these livewire forms work with static caching? I'm running into that CSRF problem, and it difficult for me to exclude these forms as they appear on a lot of my pages in the form of popups.

No big deal. I can do without static caching. Thanks.

**Comment by aerni** [comment]
Livewire doesn't work with Static Caching.

I wrote this addon for this exact reason: https://github.com/aerni/statamic-dynamic-cache

**Comment by stuartcusackie** [comment]
Thought so. Thanks for clearing that up.
